### ISSUE TITLE
Create needs components for each type of support

### ISSUE THREAD

**Issue by mewtaylor** [mmoutenot/mamas-needs-offers#2]
1. Financial resources
2. Grocery, meals, supplies, and errands (includes masks and sanitation equipment)
3. Ridesharing
4. Housing, storage, and petcare
5. In person childcare and online activities for kids
6. Emotional or spiritual support
7. Help filing for resources like unemployment, language resources, supports for undocumented folks, etc.
8. Specific items or other (i.e. doesn't fall into any category above)

**Comment by dcalacci** [comment]
Is this & #3 up to date? looking for something to help on and these seem to be finished in the current PR

**Comment by esetnik** [comment]
@dcalacci this one is partially implemented. I just did the parsing from the data and am presenting it using primarily the `DefaultContent` card. There's very little customization. See https://github.com/mmoutenot/mamas-needs-offers/blob/master/src/components/Listing/index.js#L28. If you want to start to improve the individual cards or the overall design of the `DefaultContent` that'd be great. Maybe we should consider this issue to be solved by #20 and open a new issue for styling the cards.
